name: Dart

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:dev

    steps:
      - uses: actions/checkout@v3

      - name: pub get
        run: pub get

      - name: dart format
        run: dart format --output=none --set-exit-if-changed .

      - name: dart analyze
        run: dart analyze

      # Set up some test data.
      - name: Set up test data
        run: ./tool/setup.sh

      - name: dart test
        run: dart test

      # Ensure the example works
      - name: Test example/list.dart
        run: dart example/list.dart
